name:                thinking-with-types-ex
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/thinking-with-types-ex#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  thinking-with-types-ex:
    source-dirs:      src
    main:             Main.hs
