name:                thinking-with-types-ex
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/thinking-with-types-ex#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

ghc-options:
  - -fshow-hole-constraints
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unticked-promoted-constructors


default-extensions:
  - OverloadedStrings
  - StandaloneDeriving

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:
    - exercises

executables:
  thinking-with-types-ex:
    source-dirs:      src
    main:             Main.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - exercises
      - test
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec == 2.*
      - hspec-expectations-lifted
      - QuickCheck
